//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Praised
    {
        public int PraisedID { get; set; }
        public int Users_id { get; set; }
        public Nullable<int> ComID { get; set; }
        public Nullable<int> Reply_id { get; set; }
    
        public virtual Comments Comments { get; set; }
        public virtual Reply Reply { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
