//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class XueHaiEntities : DbContext
    {
        public XueHaiEntities()
            : base("name=XueHaiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<FavoriteGoods> FavoriteGoods { get; set; }
        public virtual DbSet<FavoriteVideo> FavoriteVideo { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<GoodsK> GoodsK { get; set; }
        public virtual DbSet<LunTan> LunTan { get; set; }
        public virtual DbSet<Manager> Manager { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Reply> Reply { get; set; }
        public virtual DbSet<ShopCar> ShopCar { get; set; }
        public virtual DbSet<UserAddress> UserAddress { get; set; }
        public virtual DbSet<UserGuanzhu> UserGuanzhu { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<Video> Video { get; set; }
        public virtual DbSet<VideoK> VideoK { get; set; }
        public virtual DbSet<View_OrderDetails> View_OrderDetails { get; set; }
        public virtual DbSet<View_ShopCar> View_ShopCar { get; set; }
        public virtual DbSet<View_UserInfo> View_UserInfo { get; set; }
        public virtual DbSet<Praised> Praised { get; set; }
    
        public virtual int ShopCar_Orders(Nullable<int> users_id, string userName, string userPhone, string address, string note)
        {
            var users_idParameter = users_id.HasValue ?
                new ObjectParameter("Users_id", users_id) :
                new ObjectParameter("Users_id", typeof(int));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var userPhoneParameter = userPhone != null ?
                new ObjectParameter("UserPhone", userPhone) :
                new ObjectParameter("UserPhone", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var noteParameter = note != null ?
                new ObjectParameter("note", note) :
                new ObjectParameter("note", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ShopCar_Orders", users_idParameter, userNameParameter, userPhoneParameter, addressParameter, noteParameter);
        }
    }
}
